import type { Job } from "@/types/job";

export const SEED_JOBS: Job[] = [
  {
    id: "seed-1",
    title: "Master Electrician",
    trade: "Electrician",
    location: "Austin, TX",
    jobType: "Full-time",
    payMin: 35,
    payMax: 55,
    description: "Looking for a licensed master electrician for commercial and residential projects. Must have 5+ years experience with panel upgrades, conduit bending, and code compliance.",
    status: "Active",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "seed-2",
    title: "Commercial Plumber",
    trade: "Plumber",
    location: "Denver, CO",
    jobType: "Full-time",
    payMin: 30,
    payMax: 48,
    description: "Seeking an experienced commercial plumber for large-scale construction projects. Experience with medical gas systems and backflow prevention preferred.",
    status: "Active",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "seed-3",
    title: "HVAC Technician",
    trade: "HVAC",
    location: "Phoenix, AZ",
    jobType: "Contract",
    payMin: 28,
    payMax: 42,
    description: "Contract HVAC tech needed for seasonal maintenance and installation of commercial split systems. EPA 608 certification required.",
    status: "Active",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "seed-4",
    title: "Structural Welder",
    trade: "Welder",
    location: "Houston, TX",
    jobType: "Full-time",
    payMin: 32,
    payMax: 50,
    description: "Experienced structural welder for steel fabrication shop. Must be certified in MIG/TIG/Stick. Blueprint reading required.",
    status: "Draft",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "seed-5",
    title: "Finish Carpenter",
    trade: "Carpenter",
    location: "Nashville, TN",
    jobType: "Part-time",
    payMin: 25,
    payMax: 38,
    description: "Part-time finish carpenter for custom residential builds. Trim work, cabinetry installation, and hardwood flooring experience a plus.",
    status: "Active",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];